### PR TITLE
Added a small but neat change to the cmd_np function

### PR DESCRIPTION
**Pull request by p0thi**
a small but imo nice change to the cmd_np function, that shows a "progress bar" of the current song (Read the comments in the code for an example)
I hope you like it...

### CODE REVIEW

**Review by CyberiumShadow — COMMENTED** [review]
Is it tested to be working?

**Comment by p0thi** [comment]
Yes it is. It looks like this:
[](https://postimg.org/image/56yfmkgml/)

**Review by CyberiumShadow — APPROVED** [review]
Just tested it as well. It looks good.

**Comment by imayhaveborkedit** [comment]
This doesn't work with entries that have 0 duration.

**Comment by p0thi** [comment]
@imayhaveborkedit You were right. I fixed it. 
The only problem I am still seeing in the future is with streams. but I don't know how you are going to implement them.

**Comment by Intwala** [comment]
@dp-t-rex Hi, I did CTRL + F so I knew where to add this but I couldn't find the text 'streaming' anywhere in my original bot.py folder and also.. Is there a way you could make it so whenever someone joins the music voice channel it's shown in the text channel who has joined/left.

**Comment by p0thi** [comment]
@Intwala Hi, the 'streaming' text in the cmd_np function should be in the latest version of the review branch. Unfortunately i can not add the functionality to write in chat, if someone joined/left. You could ask @imayhaveborkedit (the developer of this bot), but i dont think this is on his agenda atm.

**Comment by Intwala** [comment]
Ok Thanks, what are the changes from your branch to the official MusicBot other than that?

**Comment by p0thi** [comment]
Nothing. Just the thing with the progress bar for the np command

**Comment by Intwala** [comment]
I couldn’t get your bot to work, I installed it the same way as I did with MusicBot, using your link on GitHub rather than MusicBots. Was I supposed to install it another way?

**Comment by LucasKeure** [comment]
I get this error on debian 8: any fix ?
cannot import name 'StreamPlaylistEntry'

**Comment by p0thi** [comment]
It should work the way you did it. make sure you are installing the review branch

**Comment by sypion** [comment]
Any chance we can get this kind of look for the `!volume` command?

**Comment by ghost** [comment]
Could you merge this with #757?

**Comment by Adeft** [comment]
Added the code. But nothing is showing. NO progress bar etc,

**Comment by ghost** [comment]
I made the progress bar and cmd_np better I've improved on it just thought I would share it

e75b9e49d1b52c5a97ab47bf96890962

**Comment by TicWE** [comment]
Hey @Jellco I'd need some help cause I get an error with the timedelta : 
Traceback (most recent call last):
  File "D:\Music Bot\musicbot\bot.py", line 2053, in on_message
    response = await handler(**handler_kwargs)
  File "D:\Music Bot\musicbot\bot.py", line 1282, in cmd_np
    song_progress = ftimedelta(timedelta(seconds=player.progress))
TypeError: unsupported type for timedelta days component: datetime.timedelta

**Comment by ghost** [comment]
@TicWE would it help if I gave you the source for my version of the np command

**Comment by ghost** [comment]
the original author of this code was credited because it was based off @p0thi  work so here

**Comment by ghost** [comment]
async def cmd_np(self, player, channel, server, message):
        """
        Usage:
            {command_prefix}np

        Displays the current song in chat.
        """

        if player.current_entry:
            if self.server_specific_data[server]['last_np_msg']:
                await self.safe_delete_message(self.server_specific_data[server]['last_np_msg'])
                self.server_specific_data[server]['last_np_msg'] = None

            # TODO: Fix timedelta garbage with util function
            song_progress = ftimedelta(timedelta(seconds=player.progress))
            song_total = ftimedelta(timedelta(seconds=player.current_entry.duration))

            streaming = isinstance(player.current_entry, StreamPlaylistEntry)
            prog_str = ('`[{progress}]`' if streaming else '`[{progress}/{total}]`').format(
                progress=song_progress, total=song_total
            )
            prog_bar_str = ''

            # percentage shows how much of the current song has already been played
            percentage = 0.0
            if player.current_entry.duration > 0:
                percentage = player.progress / player.current_entry.duration
            """
            This for loop adds  empty or full squares to prog_bar_str (it could look like
            [■■■■■■■■■■□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□]
            if for example the song has already played 25% of the songs duration
            """
            progress_bar_length = 37
            for i in range(progress_bar_length):
                if (percentage < 1 / progress_bar_length * i):
                    prog_bar_str += '▁'
                else:
                    prog_bar_str += '▂'

            action_text = 'Streaming' if streaming else 'Playing'

            if player.current_entry.meta.get('channel', False) and player.current_entry.meta.get('author', False):
                np_text = "**Song:** [ <{url}> ] queued by **{author}** \n```{progress} Song: {title}  \n {progress_bar}```".format(

                    action=action_text,
                    title=player.current_entry.title,
                    author=player.current_entry.meta['author'].name,
                    progress_bar=prog_bar_str,
                    progress=prog_str,
                    url=player.current_entry.url
                )
            else:
                np_text = "**Song:** [ <{url}> ] queued by **{author}** \n```{progress} Song: {title}  \n {progress_bar}```".format(
                    action=action_text,
                    title=player.current_entry.title,
                    progress_bar=prog_bar_str,
                    progress=prog_str,
                    url=player.current_entry.url
                )

            self.server_specific_data[server]['last_np_msg'] = await self.safe_send_message(channel, np_text)
            await self._manual_delete_check(message)
        else:
            return Response(
                'There are no songs queued! Queue something with {}play.'.format(self.config.command_prefix),
                delete_after=30
            )

**Comment by ghost** [comment]
it was barely changed aside from making it look a little more like a car radio but there @TicWE replace cmd_np with that and see if it helps

**Comment by ghost** [comment]
also I gave the bot to my friend Ozone and he improved even more on it

**Comment by ghost** [comment]
so thats what the screenshot is from

**Comment by TicWE** [comment]
Thanks for you quick response @Jellco, I get this now : 
Traceback (most recent call last):
  File "D:\Music Bot\musicbot\bot.py", line 2054, in on_message
    response = await handler(**handler_kwargs)
  File "D:\Music Bot\musicbot\bot.py", line 1282, in cmd_np
    song_progress = ftimedelta(timedelta(seconds=player.progress))
NameError: name 'ftimedelta' is not defined

I'll try defining it and I'll tell if it fixed it.

**Comment by TicWE** [comment]
That's strange, it gives the message for the command !help np when I type !np..
I don't know how to properly define it ^^'

**Comment by ghost** [comment]
@TicWE try adding this

from datetime import timedelta

**Comment by ghost** [comment]
@TicWE  I might be able to get my friend Ozone to help you with this on discord

**Comment by ghost** [comment]
@TicWE I'd have to send you his discord info like off github because I'm worried about people picking on him

**Comment by TicWE** [comment]
> @TicWE try adding this

from datetime import timedelta
I've already done this :/

**Comment by ghost** [comment]
have you updated the dependencies?

**Comment by ghost** [comment]
I would debug it and check to see if theres something wrong there

**Comment by TicWE** [comment]
Well yes I did
You can add me on discord : WarEaglesTic#2086

**Comment by ghost** [comment]
hmm who I know are you using the review branch as a base or are you using the main branch

**Comment by ghost** [comment]
because the np command that @p0thi made and I updated was designed for the code in the review branch

**Comment by ghost** [comment]
@TicWE

**Comment by TicWE** [comment]
What's different ?

**Comment by ghost** [comment]
the review branch uses a newer discord api and newer things

**Comment by ghost** [comment]
@TicWE wait you might be able to get it to work just give me a sec

**Comment by ghost** [comment]
@TicWE try to add this to your requirements.txt

discord.py[voice] ~= 0.13.0
pip
youtube_dl
colorlog
cffi --only-binary all; sys_platform == 'win32'
ignore what you already have

**Comment by ghost** [comment]
if that does work it might be a good idea to use the review branch

**Comment by ghost** [comment]
could be their too different

**Comment by ghost** [comment]
if I recall the review branch has a streaming mode and that sort of stuff so the code might be too different

**Comment by TicWE** [comment]
Still this : 
Traceback (most recent call last):
  File "D:\Music Bot\musicbot\bot.py", line 2054, in on_message
    response = await handler(**handler_kwargs)
  File "D:\Music Bot\musicbot\bot.py", line 1282, in cmd_np
    song_progress = ftimedelta(timedelta(seconds=player.progress))
NameError: name 'ftimedelta' is not defined

**Comment by ghost** [comment]
yeah use the review branch insted it should work if you do that

**Comment by TicWE** [comment]
What should I do ? x)

**Comment by ghost** [comment]
@TicWE download the review brach version of the bot and use that insted

**Comment by TicWE** [comment]
I have this now : 
Traceback (most recent call last):
  File "D:\Music Bot\musicbot\bot.py", line 2035, in on_message
    response = await handler(**handler_kwargs)
  File "D:\Music Bot\musicbot\bot.py", line 1300, in cmd_np
    prog_bar_str += '_'
UnboundLocalError: local variable 'prog_bar_str' referenced before assignment

**Comment by TicWE** [comment]
It seems to work but not totally, I have this message : 
Now Playing: Nightcore - Counting stars [00:15/02:47]

**Comment by TicWE** [comment]
Everything is Okay now :)

**Comment by Injusticecraft** [comment]
@TicWE i have that msg to but i dont have a progress bar plz someone help me

**Comment by Injusticecraft** [comment]
could someone help me update this bot to the version that everyone else seems to have

**Comment by TicWE** [comment]
Can you show me your file, so I can check what is missing ?
Send me a message on discord, I'll send you mine otherwise

**Comment by MeepCastana** [comment]
When the autoplaylist is activated i get this error 


Traceback (most recent call last):
  File "C:\Users\Doggo\Desktop\MusicBot-review 22222\musicbot\bot.py", line 2589, in on_message
    response = await handler(**handler_kwargs)
  File "C:\Users\Doggo\Desktop\MusicBot-review 22222\musicbot\bot.py", line 1848, in cmd_np
    url=player.current_entry.url
KeyError: 'author'

**Comment by ghost** [comment]
@TicWE  sorry for not responding sooner I added  you

**Comment by ghost** [comment]
@TimmyTheRat I'm not sure why that's happening

**Comment by ghost** [comment]
there are some bugs that I couldn't even figure out but I can look into it and see if i get the same issue

**Comment by ghost** [comment]
@TimmyTheRat  I am getting it and I understand the problem its a bug that relates because to the fact that the bot is playing songs on its own I can fix this and repost the source code

**Comment by ghost** [comment]
@TimmyTheRat  I have looked thru the code and its a its an error that I can not figure out the truth is I the bot configured to not use the autoplaylist I saw no need for it however that should be fixed I've compared the code to p0thi's code and my guess is it was a bug in their code but I really don't want to point fingers so sorry but idk

**Comment by MeepCastana** [comment]
Just wanted to post the bug. Maybe somebody can figure it out and fix it

**Comment by TimmyTheRat** [comment]
Add can't fix label

**Comment by MeepCastana** [comment]
I got a fix for the error. 


`    async def cmd_np(self, player, channel, server, message):
        """
        Usage:
            {command_prefix}np
    
        Displays the current song in chat.
        """

        if player.current_entry:
            if self.server_specific_data[server]['last_np_msg']:
                await self.safe_delete_message(self.server_specific_data[server]['last_np_msg'])
                self.server_specific_data[server]['last_np_msg'] = None

            # TODO: Fix timedelta garbage with util function
            song_progress = ftimedelta(timedelta(seconds=player.progress))
            song_total = ftimedelta(timedelta(seconds=player.current_entry.duration))

            streaming = isinstance(player.current_entry, StreamPlaylistEntry)
            prog_str = ('`[{progress}]`' if streaming else '`[{progress}/{total}]`').format(
                progress=song_progress, total=song_total
            )
            prog_bar_str = ''

            # percentage shows how much of the current song has already been played
            percentage = 0.0
            if player.current_entry.duration > 0:
                percentage = player.progress / player.current_entry.duration
            """
            This for loop adds  empty or full squares to prog_bar_str (it could look like
            [■■■■■■■■■■□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□]
            if for example the song has already played 25% of the songs duration
            """
            progress_bar_length = 37
            for i in range(progress_bar_length):
                if (percentage < 1 / progress_bar_length * i):
                    prog_bar_str += '□'
                else:
                    prog_bar_str += '■'

            action_text = 'Streaming' if streaming else 'Playing'

            if player.current_entry.meta.get('channel', False) and player.current_entry.meta.get('author', False):
                np_text = "**Song:** [ <{url}> ] \n```{progress} Song: {title}  \n {progress_bar}```".format(

                    action=action_text,
                    title=player.current_entry.title,
                    author=player.current_entry.meta['author'].name,
                        progress_bar=prog_bar_str,
                    progress=prog_str,
                    url=player.current_entry.url
                )
            else:
                np_text = "**Song:** [ <{url}> ] \n```{progress} Song: {title}  \n {progress_bar}```".format(
                    action=action_text,
                    title=player.current_entry.title,
                    progress_bar=prog_bar_str,
                    progress=prog_str,
                    url=player.current_entry.url
                )

            self.server_specific_data[server]['last_np_msg'] = await self.safe_send_message(channel, np_text)
            await self._manual_delete_check(message)
        else:
            return Response(
                'There are no songs queued! Queue something with {}play.'.format(self.config.command_prefix),
                delete_after=30)
            `

**Comment by ghost** [comment]
@TimmyTheRat what was wrong with it? I'd love to know how you fixed it by knowing what you changed

**Comment by MeepCastana** [comment]
"**Song:** [ <{url}> ] queued by **{author}** \n```{progress} Song: {title}  \n {progress_bar}```".format(

delete queued by **{author}**

**Comment by MeepCastana** [comment]
"Song: [ <{url}> ] \n{progress} Song: {title} \n {progress_bar}".format(

should be like this. it won't show who requested the song but it will no longer give the error message

**Comment by ghost** [comment]
@TimmyTheRat was it replaced by something else?

**Comment by MeepCastana** [comment]
no

**Comment by ghost** [comment]
ok

**Comment by MeepCastana** [comment]
capture
 it looks like this now

**Comment by MeepCastana** [comment]
Tell me if it worked for you

**Comment by MeepCastana** [comment]
After some time i finally know the issue. The np command doesn't work when autoplaylist is activated because the songs playing are not requested by anyone. 

I have no knowledge about py but i think the fix would be: 

If autoplaylist is activated show this text. Remove  queued by {author} since there is no author who requested 
"**Song:** [ <{url}> ] \n```{progress} Song: {title}  \n {progress_bar}```" 

And when autoplaylist is activated show the text like this.
"**Song:** [ <{url}> ] queued by **{author}** \n```{progress} Song: {title}  \n {progress_bar}```"

**Comment by rafaelwastaken** [comment]
If anyone wants to use markdown as seen above and keep the boxes, these ones look better when used with markdown. 
```
                prog_bar_str += '⬜'
            else:
                prog_bar_str += '⬛'
```
Here's an example of how they look. 
image


imo, the original boxes looked kinda squished together when used in markdown boxes

**Comment by sypion** [comment]
@fofofofofofofofoXD I see that you're using custom embedding with the bot? How do you do this? I'd love to apply it to the current local repository I have of this bot.

**Comment by Xylems** [comment]
Im getting a log message that it shows the following as bad syntax

`    if player.current_entry:
        if self.server_specific_data[server]['last_np_msg']:
            await self.safe_delete_message(self.server_specific_data[server]['last_np_msg'])
            self.server_specific_data[server]['last_np_msg'] = None`

**Comment by MeepCastana** [comment]
whats the message

**Comment by Hydrophoby** [comment]
Traceback (most recent call last):
  File "run.py", line 162, in main
    from musicbot import MusicBot
  File "C:\Users\...\Desktop\Music bot\musicbot\__init__.py", line 1, in
<module>
    from .bot import MusicBot
  File "C:\Users\...\Desktop\Music bot\musicbot\bot.py", line 1455
    await self.safe_delete_message(self.server_specific_data[server]['last_np_ms
g'])
             ^
SyntaxError: invalid syntax

**Comment by MeepCastana** [comment]
Use this command 



async def cmd_np(self, player, channel, server, message):
"""
Usage:
{command_prefix}np

    Displays the current song in chat.
    """

    if player.current_entry:
        if self.server_specific_data[server]['last_np_msg']:
            await self.safe_delete_message(self.server_specific_data[server]['last_np_msg'])
            self.server_specific_data[server]['last_np_msg'] = None

        # TODO: Fix timedelta garbage with util function
        song_progress = ftimedelta(timedelta(seconds=player.progress))
        song_total = ftimedelta(timedelta(seconds=player.current_entry.duration))

        streaming = isinstance(player.current_entry, StreamPlaylistEntry)
        prog_str = ('`[{progress}]`' if streaming else '`[{progress}/{total}]`').format(
            progress=song_progress, total=song_total
        )
        prog_bar_str = ''

        # percentage shows how much of the current song has already been played
        percentage = 0.0
        if player.current_entry.duration > 0:
            percentage = player.progress / player.current_entry.duration
        """
        This for loop adds  empty or full squares to prog_bar_str (it could look like
        [■■■■■■■■■■□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□]
        if for example the song has already played 25% of the songs duration
        """
        progress_bar_length = 37
        for i in range(progress_bar_length):
            if (percentage < 1 / progress_bar_length * i):
                prog_bar_str += '□'
            else:
                prog_bar_str += '■'

        action_text = 'Streaming' if streaming else 'Playing'

        if player.current_entry.meta.get('channel', False) and player.current_entry.meta.get('author', False):
            np_text = "**Song:** [ <{url}> ] \n```{progress} Song: {title}  \n {progress_bar}```".format(

                action=action_text,
                title=player.current_entry.title,
                author=player.current_entry.meta['author'].name,
                    progress_bar=prog_bar_str,
                progress=prog_str,
                url=player.current_entry.url
            )
        else:
            np_text = "**Song:** [ <{url}> ] \n```{progress} Song: {title}  \n {progress_bar}```".format(
                action=action_text,
                title=player.current_entry.title,
                progress_bar=prog_bar_str,
                progress=prog_str,
                url=player.current_entry.url
            )

        self.server_specific_data[server]['last_np_msg'] = await self.safe_send_message(channel, np_text)
        await self._manual_delete_check(message)
    else:
        return Response(
            'There are no songs queued! Queue something with {}play.'.format(self.config.command_prefix),
            delete_after=30)

**Comment by Xylems** [comment]
await self.safe_delete_message(self.server_specific_data[server]['last_np_msg']
             ^
SyntaxError: invalid Syntax

the carrot is under the "f" from the first self

**Comment by Xylems** [comment]
the carrot is under the "f" from the first self

**Comment by Xylems** [comment]
Still getting invalid syntax

**Comment by sypion** [comment]
@Xylems That is your issue. Check your spaces/indentations. If you're still having syntax problems, go learn Python.

**Comment by sypion** [comment]
If you're still having issues, go learn Python.

**Comment by Xylems** [comment]
@sypion thanks for the tip to check indentations, i indented once too many. As far as the go learn Python comment that was a bit uncalled for as i am sure many people who try to run this do not know python.

**Comment by sypion** [comment]
@Xylems You don't need to know Python to run the bot; only to modify it which isn't supported in the first place.

**Comment by rafaelwastaken** [comment]
@sypion Were you the person that asked me about using embeds with the bot last month? I got an alert saying someone with a name similar to yours asked the question but the message appears to have been deleted.

**Comment by sypion** [comment]
@fofofofofofofofoXD I figured it out in the end.

**Comment by MeepCastana** [comment]
@fofofofofofofofoXD i wanna know if possible 😃

**Comment by rafaelwastaken** [comment]
@TimmyTheRat I personally made a copy of the safe_send_message method called safe_send_embed and modified it to work with embeds. To use them though, you'll need to use discord.py v0.15.0+ since v0.15 added support for rich embeds.

you can do some pretty cool stuff like this if you make all the necessary modifications 😃 
image

**Comment by sypion** [comment]
@fofofofofofofofoXD I'd love to modify the local repository I have of the music bot the same way you do. If you can show me specifically how to, that'd be awesome. When trying to update to discord.py v0.15.0, music bot starts breaking.

**Comment by MeepCastana** [comment]
Same thing happens to me. When i updated discord.py to 0.15 the music bot stopped working and gave me a bunch of errors.

**Comment by rafaelwastaken** [comment]
What does the error say? I've been using discord.py 0.16+ for months now without any problems

**Comment by MeepCastana** [comment]
cannot import name '_func_'
running python 3.6

**Comment by Camdog-python** [comment]
Hey how do i use this new thingo? im new to this sorry. :)

**Comment by buhhhrandon** [comment]
I get a "song_progress = ftimedelta(timedelta(seconds=player.progress))
NameError: name 'ftimedelta' is not defined" All other commands work, when using the "np" command, nothing shows.

**Comment by OzzyHelix** [comment]
I made a version of it @p0thi what do you think of this change?
764eb6e1385dfe61032df147185f45d6

**Comment by OzzyHelix** [comment]
@fofofofofofofofoXD  how did you do that? because that looks awesome

**Comment by Intwala** [comment]
Are any of these bots third party and do you mind if I invite to my server if any of you don't mind?

**Comment by OzzyHelix** [comment]
@Intwala the version of the bot that I have is customized for a couple of servers that my friends use so sorry

**Comment by MattBSG** [comment]
Alright, please resolve conflicts and update to work with the latest review branch or I’ll close this for inactivity soon.

**Comment by p0thi** [comment]
I have no time to do it atm. Sorry for that.

**Comment by OzzyHelix** [comment]
@MattBSG @p0thi I didn't really feel like I had a place to speak here but I have been able to use p0thi's now playing system in one of my bot's if its ok I might be able to make a pull request to update p0thi's branch

**Comment by MattBSG** [comment]
If you feel like doing that @OzoneHelix then go ahead! Make sure to mention this PR.

**Comment by OzzyHelix** [comment]
on p0thi fork I left a PR with the updated bot I'm leaving the decision up to @p0thi on whether they want to use it or not again it's their code and pull request I just figured if they didn't have time I'd do them a favor and update it for them again I'm leaving the decision up to them on whether they want to continue with the PR if they do then merging my PR on their fork will make it up to date with the review branch

**Comment by OzzyHelix** [comment]
oh yeah forgot the i18n file and bot.py were changed to take advance of the useEmbed I wasn't sure if it was going to conflict

**Comment by OzzyHelix** [comment]
I think the conflicts relate to these 
image
image

**Comment by OzzyHelix** [comment]
I believe for the most part its up to date aside from this conflicts not sure why

**Comment by OzzyHelix** [comment]
if any help is need about this let me know forgive me I'm just trying to be helpful

**Comment by p0thi** [comment]
@MattBSG I think it is now ready to work with the latest branch.
Thank you @OzoneHelix for the help!

**Comment by ghost** [comment]
@p0thi np I was going to send you another PR to fix the conflicts but you seem to figure it out

**Comment by ghost** [comment]
sorry wrong account
